name: ci

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  ci:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest]
        node: [16, 18]

    steps:
      - name: Checkout 🛎
        uses: actions/checkout@master

      - name: Setup node env 🏗
        uses: actions/setup-node@v2.5.0
        with:
          node-version: ${{ matrix.node }}
          check-latest: true

      - name: setup PnpM
        run: "npm i -g pnpm"

      - name: Get yarn cache directory path 🛠
        run: echo "INOP"
#        id: yarn-cache-dir-path
#        run: echo "::set-output name=dir::$(yarn cache dir)"

      - name: Cache node_modules 📦
        run: echo "INOP"
#      - name: Cache node_modules 📦
#        uses: actions/cache@v2.1.7
#        id: yarn-cache # use this to check for `cache-hit` (`steps.yarn-cache.outputs.cache-hit != 'true'`)
#        with:
#          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
#          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
#          restore-keys: |
#            ${{ runner.os }}-yarn-

      - name: Install dependencies 👨🏻‍💻
        run: pnpm i

      - name: Run linter 👀
        run: pnpm lint

      - name: Run build 🏗
        #run: yarn build
        run: pnpm build

